# Generated by Django 4.1.3 on 2022-11-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synths',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='synths',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
