# Generated by Django 4.1.3 on 2022-11-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synths', '0002_rename_create_at_synths_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synths',
            name='file_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='synths',
            name='file_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
