# Generated by Django 4.1.3 on 2022-11-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synths', '0003_synths_file_name_synths_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebay_Synths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('categoryname', models.CharField(max_length=1000)),
                ('selling_status', models.CharField(max_length=1000)),
                ('cost', models.CharField(max_length=1000)),
                ('item_currency', models.CharField(max_length=1000)),
                ('shipping_cost', models.CharField(max_length=1000)),
                ('shipping_to', models.CharField(max_length=1000)),
                ('shipping_currency', models.CharField(max_length=1000)),
                ('condition', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('watcher_count', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('synth_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_synths', to='synths.synths')),
            ],
        ),
    ]
